export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const SET_BASKET = 'SET_BASKET';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
export const SET_PRODUCTLIST = 'SET_PRODUCTLIST';
export const CALCULATE_TOTAL_PRICE= 'CALCULATE_TOTAL_PRICE'

export const LOGIN_NEW_USER= 'LOGIN_NEW_USER';
export const SET_EMAIL = 'SET_EMAIL'
export const SET_EMAIL_ERROR = 'SET_EMAIL_ERROR'
export const SET_PASSWORD_ERROR = 'SET_PASSWORD_ERROR'
export const CUSTOMER_LOGIN = 'CUSTOMER_LOGIN'
export const CUSTOMER_LOGOUT = 'CUSTOMER_LOGOUT'
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT'



